export const runEntries = [
  {
    date: "01/02/2021",
    location: "Philadelphia, PA",
    distance: "5",
    hours: "00",
    minutes: "20",
    seconds: "30",
    weather: "clear",
    surface: "pavement",
    terrain: "mixed",
    notes: "Good training run!",
    public: false,
  },
  {
    date: "01/01/2021",
    location: "Haddonfield, NJ",
    distance: "5",
    hours: "00",
    minutes: "20",
    seconds: "30",
    weather: "clear",
    surface: "pavement",
    terrain: "mixed",
    notes: "Good training run!",
    public: false,
  },
  {
    date: "12/25/2020",
    location: "Philadelphia, PA",
    distance: "5",
    hours: "00",
    minutes: "20",
    seconds: "30",
    weather: "snow",
    surface: "pavement",
    terrain: "mixed",
    notes: "Christmas! Nothing better than a run to celebrate.",
    public: false,
  },
];